### PR TITLE
crystal 0.35 compability

### PR DESCRIPTION
**Pull request by carlhoerberg**

### CODE REVIEW

**Comment by straight-shoota** [comment]
Just a heads up: The breaking change is probably going to be reverted in Crystal 0.35.1 (https://github.com/crystal-lang/crystal/pull/9469), making the IO changes in this PR obsolete (and also #36).
The compress changes are still good, though.

**Comment by straight-shoota** [comment]
@carlhoerberg Would you mind removing the IO changes from this PR. They're no longer necessary (and indeed incompatible) with Crystal 0.35.1.

**Comment by carlhoerberg** [comment]
updated

**Comment by straight-shoota** [comment]
Fixed in #38. Tt's basically the same change but also fixes return types on abstract method overrides (see #35). Thanks anyway!

**Pull request closed without merging**
