### PR TITLE
Run Travis CI against Crystal nightlies

### PR DESCRIPTION
**Pull request by Sija**
SSIA

### CODE REVIEW

**Comment by Sija** [comment]
@schovi 🏓

**Comment by Sija** [comment]
Btw, in order for the CI to pass you'd need to do sth along the lines of https://github.com/stumpycr/stumpy_png/issues/34.

**Comment by Sija** [comment]
@schovi Hello, any chances on getting this reviewed/merged?

**Review by straight-shoota — APPROVED** [review]

**Comment by Sija** [comment]
@straight-shoota CI is 💚  btw - see https://travis-ci.org/github/schovi/baked_file_system/builds/738983764

**Comment by straight-shoota** [comment]
Unfortunately, I can't merge because travis status doesn't report in Github. I can't push directly to master branch either, because it's protected.

**Comment by Sija** [comment]
@straight-shoota That's a bummer since @schovi doesn't seem to be active...

**Comment by schovi** [comment]
fixed by https://github.com/schovi/baked_file_system/pull/41 🙏

**Pull request closed without merging**
